//
// Created by Kaleb Smith on 12/9/21.
//

#ifndef DATALOG_STRONGLYCONNECTEDCOMPONENT_H
#define DATALOG_STRONGLYCONNECTEDCOMPONENT_H


class StronglyConnectedComponent {

};


#endif //DATALOG_STRONGLYCONNECTEDCOMPONENT_H
